name: Images for Pterodactyl GraalVM

on:
  push:
    branches: 
      - main
    paths:
      - Pterodactyl/GraalVM/**

jobs:
  push:
    name: "Pterodactyl-GraalVM-${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - jdk8-ee
          - jdk11
          - jdk11-ee
          - jdk17
          - jdk17-ee
          - jdk20
          - jdk21
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "latest"
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Pterodactyl
          file: ./Pterodactyl/GraalVM/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/akticube/containers:pterodactyl-graalvm-${{ matrix.version }}
