name: Images for Pterodactyl GraalVM

on:
  push:
    branches: 
      - main
    paths:
      - Pterodactyl/GraalVM/**

jobs:
  push:
    name: "Pterodactyl-GraalVM-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - jdk11
          - jdk17
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Pterodactyl
          file: ./Pterodactyl/GraalVM/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/akticube/containers:pterodactyl-graalvm-${{ matrix.tag }}