name: Images for Pterodactyl GraalVM

on:
  push:
    branches: 
      - main
    paths:
      - Pterodactyl/GraalVM/**

jobs:
  push:
    name: "Pterodactyl-GraalVM-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - jdk8-ee
          - jdk11
          - jdk11-ee
          - jdk17
          - jdk17-ee
          - jdk20
          - jdk21
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Pterodactyl
          file: ./Pterodactyl/GraalVM/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/akticube/containers:pterodactyl-graalvm-${{ matrix.version }}
