name: Images for Pterodactyl GraalVM arm64

on:
  push:
    branches: 
      - main
    paths:
      - Pterodactyl/GraalVM-arm64/**

jobs:
  push:
    name: "Pterodactyl-GraalVM-ARM64-${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - jdk11
          - jdk11-ee
          - jdk17
          - jdk17-ee
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "latest"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Pterodactyl
          file: ./Pterodactyl/GraalVM-arm64/${{ matrix.version }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/akticube/containers:pterodactyl-graalvm-${{ matrix.version }}-arm64